#!/bin/sh
set -e

service_name="docker-veth-namer.service"

if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask "${service_name}" >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge "${service_name}" >/dev/null || true
		deb-systemd-helper unmask "${service_name}" >/dev/null || true
	fi
fi
