#!/bin/sh
set -e

service_name="docker-veth-namer.service"

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed "${service_name}"; then
		# This will only remove masks created by d-s-h on package removal.
		deb-systemd-helper unmask "${service_name}" >/dev/null || true

		if deb-systemd-helper --quiet was-enabled "${service_name}"; then
			# Create new symlinks, if any.
			deb-systemd-helper enable "${service_name}" >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state "${service_name}" >/dev/null || true
fi

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			deb-systemd-invoke try-restart "${service_name}" >/dev/null || true
		fi
	fi
fi
